# Generated by Django 3.2.9 on 2021-12-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoSurPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='infoEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enf', models.CharField(max_length=100)),
                ('prenom_enf', models.CharField(max_length=100)),
                ('Date_De_Naissance_enf', models.DateField(auto_now_add=True)),
                ('lieu_De_Naissance_enf', models.CharField(max_length=100)),
                ('nom_pere', models.CharField(max_length=100)),
                ('Date_De_Naissance_pere', models.DateField()),
                ('lieu_De_Naissance_pere', models.CharField(max_length=100)),
                ('fonction_pere', models.CharField(max_length=100)),
                ('nom_mere', models.CharField(max_length=100)),
                ('Date_De_Naissance_mere', models.DateField()),
                ('lieu_De_Naissance_mere', models.CharField(max_length=100)),
                ('fonction_mere', models.CharField(max_length=100)),
                ('infoSurPersonnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnfantEnregistre.infosurpersonnel')),
            ],
        ),
    ]
